%YAML 1.2
---
CHORES_LIST: 
  - [Готовка, ОБЯЗ]
  - [Покупка продуктов, ОБЯЗ]
  - [Загрузка посудомойки, ОБЯЗ]
  - [Разгрузка посудомойки, ОБЯЗ]
  - [Загрузить стиралку, ОБЯЗ]
  - [Разгрузить стиралку, ОБЯЗ]
  - [Помыть ванну, АУК]
  - [Помыть унитаз, АУК]
  - [Помыть раковину на кухне, АУК]
  - [Помыть раковину в туалете, АУК]
  - [Помыть раковину в ванне, АУК]
  - [Помыть зеркало в ванне, АУК]
  - [Помыть зеркало в туалете, АУК]
  - [Помыть зеркала в прихожей, АУК]
  - [Помыть столы на кухне, АУК]
  - [Помыть пол в прихожей, АУК]
  - [Помыть пол на кухне, АУК]
  - [Пропылесосить ковер в прихожей, АУК]
  - [Пропылесосить ковер в комнате, АУК]
  - [Пропылесосить и помыть полки, АУК]
  - [Вынести мусор, БОНУС]

CHORE_TYPES: [ОБЯЗ, АУК, БОНУС]

WEEKDAYS_LIST: [ПН, ВТ, СР, ЧТ, ПТ, СБ, ВС]

USERS_LIST: [Алекс, Саша, Андрей]